name: SWF
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.0.2
  - numpy=1.14.3
  - pip=9.0.3
  - python=3.6.8
  - scipy=1.1.0
  - seaborn=0.8.1
  - pytorch==0.4.1
  - torchvision=0.2.1
  - cuda91
  - pip:
    - tensorboardx==1.2
